spring.application.name=WebTechMidExam

# --- Database (PostgreSQL) ---
# Replace values when you create the DB.
spring.datasource.url=jdbc:postgresql://localhost:5432/one_healthline_connect
spring.datasource.username=postgres
spring.datasource.password=urban
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
